# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(blank=True, choices=[('party-event', 'Party Event'), ('governing-body-event', 'Governing Body Event'), ('volunteer', 'Volunteering Event')], max_length=255, null=True)),
                ('recurrences', recurrence.fields.RecurrenceField(null=True)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Venue')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('organization_type', models.CharField(blank=True, choices=[('democratic', 'Democratic Party Organization'), ('governing-body', 'Governing Body'), ('progressive', 'Progressive Organization'), ('candidate', 'Political Candidate')], max_length=255, null=True)),
            ],
        ),
    ]
