# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 21:54
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.TimeField(default=core.models.round_two_hours),
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.TimeField(default=core.models.round_hours),
        ),
    ]
