# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 04:26
from __future__ import unicode_literals

from django.db import migrations, models


def auto_save_venues(apps, schema_editor):
    print "supsss"
    Venue = apps.get_model('core', 'Venue')
    for v in Venue.objects.all():
        v.save()



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=255),
        ),
        migrations.RunPython(auto_save_venues, reverse_code=migrations.RunPython.noop)
    ]
