# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 21:21
from __future__ import unicode_literals

from django.db import migrations, models


def auto_save_events(apps, schema_editor):
    Event = apps.get_model('core', 'Event')
    for e in Event.objects.all():
        e.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160531_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=255),
        ),
        migrations.RunPython(auto_save_events, reverse_code=migrations.RunPython.noop)
    ]
