# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 21:22
from __future__ import unicode_literals

from django.db import migrations, models


def auto_save_organizations(apps, schema_editor):
    Organization = apps.get_model('core', 'Organization')
    for o in Organization.objects.all():
        o.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=255),
        ),
        migrations.RunPython(auto_save_organizations, reverse_code=migrations.RunPython.noop)
    ]
