# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-24 22:27
from __future__ import unicode_literals

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organization_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('party-event', 'Party Event'), ('governing-body-event', 'Governing Body Event'), ('volunteer', 'Volunteering Event'), ('advocacy', 'Advocacy'), ('rally', 'Rally'), ('forum', 'Forum'), ('community', 'Community Meetup'), (None, 'Uncategorized Event')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrences',
            field=core.fields.MoneypatchedRecurrenceField(null=True),
        ),
    ]
